@echo off
echo [+] Downloading RustDesk Portable (v1.4.0)...
powershell -Command "Invoke-WebRequest -Uri 'https://github.com/rustdesk/rustdesk/releases/download/1.4.0/rustdesk-1.4.0-x86_64.zip' -OutFile 'rustdesk.zip'"

echo [+] Extracting...
powershell -Command "Expand-Archive -Path 'rustdesk.zip' -DestinationPath '.'"

echo [+] Launching RustDesk (Console)...
start rustdesk\rustdesk.exe

echo [+] Waiting...
timeout /t 5
